cookie:
  expiry_days: 365
  key: random_key
  name: random_cookie_name
credentials:
  usernames:
    admin:
      email: nucleus526@gmail.com
      failed_login_attempts: 0
      first_name: admin
      last_name: account
      logged_in: false
      password: $2b$12$IWhft6efAFiR.XZVtAF1je9eLYmfv6j/GxYfLoJ7qtni2kbXUORFO
      password_hint: none
      roles: administrator
    test:
      email: ldg8781@naver.com
      failed_login_attempts: 0
      first_name: debug
      last_name: account
      logged_in: false
      password: $2b$12$jhKmNDXnMQt5xdXqEYJh2ewCLMMDfQ7qOaxZGH357LsK8PvWFkPfq
      password_hint: capital p!
      roles: debugger
    toda1979:
      email: oda@snu.ac.kr
      failed_login_attempts: 0
      first_name: Takuji
      last_name: Oda
      logged_in: true
      password: $2b$12$lM4Qd8M3bP.ryR05D9KVueF38ZqzcQPuJi9C5O7CMn9WIFNVgiGG.
      password_hint: Name
      roles: null
pre-authorized:
- ldg8781@snu.ac.kr
- abc@def.gh
- ijk@lmn.op
